### ISSUE TITLE
Initialise fields outside of `get_solver`

### ISSUE THREAD

**Issue by ddundo** [mesh-adaptation/goalie#179]
Instead of initialising fields inside `get_solver`, I think it would be better to do that somewhere inside `MeshSeq`. That way we do not require the user to properly name the functions (`"field"` and `"field_old"`) and assigning initial conditions to `field_old`. I think it would be good to hide this inner working of goalie from the user.

So, for example, the `burgers.py` demo is currently:
```
def get_solver(mesh_seq):
    def solver(index, ic):
        function_space = mesh_seq.function_spaces["u"][index]
        u = Function(function_space, name="u")

        # Initialise 'lagged' solution
        u_ = Function(function_space, name="u_old")
        u_.assign(ic["u"])
        ...
```
but would be simplified to
```
def get_solver(mesh_seq):
    def solver(index):                  # no longer passing ic
        u, u_ = mesh_seq.fields["u"]    # now mesh_seq.fields returns a dictionary
        ...
```

What do you think @jwallwork23?

**Comment by stephankramer** [comment]
Ok, so let's start with this one. I think you have to spell out a bit more what you are proposing. From the code above I gather you will have `goalie` _prepare_ the contents of `mesh_seq.fields`, before goalie calls the solver, such that it contains the `u` and `u_` that you *require* the user code to use as the end-of-timestep and beginning-of-timestep solution in each of the timesteps in the solver,   I'm just trying to spell out the sort of assumptions you are making that you need to explain, in order to be able to discuss the changes you are proposing. So please correct me if this description is wrong. You need to be very explicit here and describe things in terms of user code, what goalie does and expects, and what the interface is like.

So that use of `mesh_seq.fields` seems a bit of a funny way to pass on some arguments to a function, why not just have these `u` and `u_` passed in as argument?

My main concern is that you are now telling the user code which functions it *has to* use, rather than having the user create these and tell goalie which ones they are using. This doesn't work well with coupling goalie with existing models that already do this allocation for you - which is typically required because it (the existing model code) is also in charge of creating the solver objects (NonLinearVariationalSolver etc.) that have these wired in.

**Comment by ddundo** [comment]
Thanks @stephankramer, I did not consider the case where we might not want this - and I am still struggling to imagine the scenario which you are talking about without seeing an actual example :)

But if I understand you right, this can be very easily addressed. Let me copy the `burgers.py`'s `get_solver` function here so I can clearly demonstrate:
```
def get_solver(mesh_seq):
    def solver(index, ic):
        function_space = mesh_seq.function_spaces["u"][index]
        u = Function(function_space, name="u")

        # Initialise 'lagged' solution
        u_ = Function(function_space, name="u_old")
        u_.assign(ic["u"])

        # Define form
        F = mesh_seq.form(index, {"u": (u, u_)})["u"]

        # Time integrate from t_start to t_end
        P = mesh_seq.time_partition
        t_start, t_end = P.subintervals[index]
        dt = P.timesteps[index]
        t = t_start
        while t < t_end - 1.0e-05:
            solve(F == 0, u, ad_block_tag="u")
            u_.assign(u)
            t += dt
        return {"u": u}

    return solver
```
With the changes in #182, the dictionary `MeshSeq.fields` holds solutions at the current timestep (so we should probably rename it to something more informative, see https://github.com/mesh-adaptation/goalie/pull/182#discussion_r1580789499). So at the beginning of `get_solver` this is the dictionary of initial conditions at that subinterval. 

So, the below is equivalent to above (I labelled changed lanes with NEW so you can easily see what's been changed):
```
def get_solver(mesh_seq):
    def solver(index):  # NEW: INITIAL CONDITIONS NO LONGER PASSED
        # NEW: get the initial condition
        ic = mesh_seq.fields["u"][1]

        function_space = mesh_seq.function_spaces["u"][index]
        u = Function(function_space, name="u")

        # Initialise 'lagged' solution
        u_ = Function(function_space, name="u_old")
        u_.assign(ic)  # NEW

        # NEW: replace in mesh_seq.fields
        mesh_seq.fields["u"] = (u, u_)

        # Define form
        F = mesh_seq.form(index)["u"]

        # Time integrate from t_start to t_end
        P = mesh_seq.time_partition
        t_start, t_end = P.subintervals[index]
        dt = P.timesteps[index]
        t = t_start
        while t < t_end - 1.0e-05:
            solve(F == 0, u, ad_block_tag="u")
            yield  # NEW
            u_.assign(u)
            t += dt

    return solver
```

So this new approach doesn't limit us to make changes like this, I think. Does that make sense?

**Comment by ddundo** [comment]
And to answer more specifically...

> From the code above I gather you will have `goalie` _prepare_ the contents of `mesh_seq.fields`, before goalie calls the solver, such that it contains the `u` and `u_` that you _require_ the user code to use as the end-of-timestep and beginning-of-timestep solution in each of the timesteps in the solver (...) My main concern is that you are now telling the user code which functions it _has to_ use, rather than having the user create these and tell goalie which ones they are using.

The new function I introduced, `MeshSeq._reinitialise_fields` prepares functions `u` and `u_` based on the information the user provided in `get_function_spaces` - i.e. the name of the field and associated function space. So I wouldn't say that I am "requiring" or restricting the user. The user can still use whatever they want, they just need to specify it in `get_function_spaces`.

**Comment by ddundo** [comment]
> So that use of `mesh_seq.fields` seems a bit of a funny way to pass on some arguments to a function, why not just have these `u` and `u_` passed in as argument?

Actually the more I think about it, I'm not sure if I agree... if we do that, where do we stop? Should we also pass `mesh_seq.function_spaces`, `mesh_seq.form`, `mesh_seq.time_partition`, etc. as arguments?
